#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Returns dialogue from Monty Python and the Holy Grail. 
   Creates variable SPANISH which contains the part of the dialogue 
   about the Spanish Inqistion from Monty Python and the Holy Grail. 
   Also, the line is associated with the movie Sliding Doors. 
"""
SPANISH = '''Nobody expects the Spanish Inquisition!
Our chief weapon is surprise...surprise and fear...fear and surprise....
Our two weapons are fear and surprise...and ruthless efficiency....
Our three weapons are fear, surprise, and ruthless efficiency... .
and an almost fanatical devotion to the Pope....
Our four...no... amongst our weapons....
amongst our weaponry are such elements as fear, surprise....
I'll come in again.'''
